"""Add last_notified_at to reminders for spam prevention

Revision ID: 58721921d48e
Revises: a662822bf6ea
Create Date: 2026-01-16 08:40:54.682042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "58721921d48e"
down_revision: Union[str, Sequence[str], None] = "a662822bf6ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reminders", sa.Column("last_notified_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f("ix_reminders_last_notified_at"), "reminders", ["last_notified_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reminders_last_notified_at"), table_name="reminders")
    op.drop_column("reminders", "last_notified_at")
    # ### end Alembic commands ###
