"""Add action_items and bookmarks tables

Revision ID: 5a8b13d16ac1
Revises: 58721921d48e
Create Date: 2026-01-19 20:36:31.541338

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5a8b13d16ac1"
down_revision: Union[str, Sequence[str], None] = "58721921d48e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "action_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=5000), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="actionitemstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "entity_type",
            sa.Enum(
                "PERSON",
                "CLIENT",
                "PROJECT",
                "EMPLOYER",
                "WORK_SESSION",
                "MEETING",
                "NOTE",
                "REMINDER",
                "ACTION_ITEM",
                "BOOKMARK",
                name="entitytype",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column(
            "privacy_level",
            sa.Enum("PUBLIC", "INTERNAL", "PRIVATE", name="privacylevel", native_enum=False),
            nullable=False,
        ),
        sa.Column("tags", postgresql.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_action_items_due_date"), "action_items", ["due_date"], unique=False)
    op.create_index(
        "ix_action_items_entity", "action_items", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(op.f("ix_action_items_status"), "action_items", ["status"], unique=False)
    op.create_index(
        "ix_action_items_status_due_date", "action_items", ["status", "due_date"], unique=False
    )
    op.create_table(
        "bookmarks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column(
            "entity_type",
            sa.Enum(
                "PERSON",
                "CLIENT",
                "PROJECT",
                "EMPLOYER",
                "WORK_SESSION",
                "MEETING",
                "NOTE",
                "REMINDER",
                "ACTION_ITEM",
                "BOOKMARK",
                name="entitytype",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column(
            "privacy_level",
            sa.Enum("PUBLIC", "INTERNAL", "PRIVATE", name="privacylevel", native_enum=False),
            nullable=False,
        ),
        sa.Column("tags", postgresql.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_bookmarks_entity", "bookmarks", ["entity_type", "entity_id"], unique=False)
    op.alter_column(
        "clients",
        "tags",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=None,
        existing_nullable=False,
    )
    op.add_column(
        "employers",
        sa.Column("tags", postgresql.ARRAY(sa.String()), server_default="{}", nullable=False),
    )
    op.add_column(
        "notes",
        sa.Column("tags", postgresql.ARRAY(sa.String()), server_default="{}", nullable=False),
    )
    op.alter_column(
        "people",
        "tags",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=None,
        existing_nullable=False,
    )
    op.add_column(
        "projects",
        sa.Column("tags", postgresql.ARRAY(sa.String()), server_default="{}", nullable=False),
    )
    op.alter_column(
        "reminders",
        "tags",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=None,
        existing_nullable=False,
    )
    op.add_column(
        "work_sessions",
        sa.Column("tags", postgresql.ARRAY(sa.String()), server_default="{}", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("work_sessions", "tags")
    op.alter_column(
        "reminders",
        "tags",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=sa.text("'{}'::character varying[]"),
        existing_nullable=False,
    )
    op.drop_column("projects", "tags")
    op.alter_column(
        "people",
        "tags",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=sa.text("'{}'::character varying[]"),
        existing_nullable=False,
    )
    op.drop_column("notes", "tags")
    op.drop_column("employers", "tags")
    op.alter_column(
        "clients",
        "tags",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=sa.text("'{}'::character varying[]"),
        existing_nullable=False,
    )
    op.drop_index("ix_bookmarks_entity", table_name="bookmarks")
    op.drop_table("bookmarks")
    op.drop_index("ix_action_items_status_due_date", table_name="action_items")
    op.drop_index(op.f("ix_action_items_status"), table_name="action_items")
    op.drop_index("ix_action_items_entity", table_name="action_items")
    op.drop_index(op.f("ix_action_items_due_date"), table_name="action_items")
    op.drop_table("action_items")
    # ### end Alembic commands ###
