"""Make project on_behalf_of_id nullable

Revision ID: 962c0bbfa59e
Revises: f4e1841d043f
Create Date: 2026-01-15 14:32:22.374124

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "962c0bbfa59e"
down_revision: Union[str, Sequence[str], None] = "f4e1841d043f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("projects", "on_behalf_of_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("projects", "on_behalf_of_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
