"""Make note entity_type and entity_id nullable

Revision ID: a662822bf6ea
Revises: 962c0bbfa59e
Create Date: 2026-01-15 14:33:03.584946

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a662822bf6ea"
down_revision: Union[str, Sequence[str], None] = "962c0bbfa59e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("notes", "entity_type", existing_type=sa.VARCHAR(length=12), nullable=True)
    op.alter_column("notes", "entity_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("notes", "entity_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("notes", "entity_type", existing_type=sa.VARCHAR(length=12), nullable=False)
    # ### end Alembic commands ###
