"""add_title_and_tags_to_meeting

Revision ID: ef648c8126f5
Revises: f686bea1590c
Create Date: 2026-01-15 13:08:01.436514

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ef648c8126f5"
down_revision: Union[str, Sequence[str], None] = "f686bea1590c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meetings",
        sa.Column(
            "title", sa.String(length=500), server_default="Untitled Meeting", nullable=False
        ),
    )
    op.add_column(
        "meetings",
        sa.Column("tags", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
    )
    # Remove server_default after column is created (only needed for existing rows)
    op.alter_column("meetings", "title", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meetings", "tags")
    op.drop_column("meetings", "title")
    # ### end Alembic commands ###
