"""Initial schema

Revision ID: f686bea1590c
Revises:
Create Date: 2026-01-15 10:55:05.071479

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f686bea1590c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            sa.Enum("COMPANY", "INDIVIDUAL", name="clienttype", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "PAST", name="clientstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("contact_info", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clients_name"), "clients", ["name"], unique=False)
    op.create_table(
        "employers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("is_self", sa.Boolean(), nullable=False),
        sa.Column("contact_info", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employers_name"), "employers", ["name"], unique=False)
    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=5000), nullable=False),
        sa.Column(
            "privacy_level",
            sa.Enum("PUBLIC", "INTERNAL", "PRIVATE", name="privacylevel", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "entity_type",
            sa.Enum(
                "PERSON",
                "CLIENT",
                "PROJECT",
                "EMPLOYER",
                "WORK_SESSION",
                "MEETING",
                "REMINDER",
                name="entitytype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_notes_entity", "notes", ["entity_type", "entity_id"], unique=False)
    op.create_table(
        "people",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("linkedin_url", sa.String(length=500), nullable=True),
        sa.Column("is_stakeholder", sa.Boolean(), nullable=False),
        sa.Column("additional_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_people_email"), "people", ["email"], unique=False)
    op.create_index(op.f("ix_people_full_name"), "people", ["full_name"], unique=False)
    op.create_table(
        "reminders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("due_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("text", sa.String(length=1000), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("recurrence_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "related_entity_type",
            sa.Enum(
                "PERSON",
                "CLIENT",
                "PROJECT",
                "EMPLOYER",
                "WORK_SESSION",
                "MEETING",
                "REMINDER",
                name="entitytype",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("related_entity_id", sa.Integer(), nullable=True),
        sa.Column("snoozed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_reminders_active", "reminders", ["due_time", "is_completed"], unique=False)
    op.create_index(op.f("ix_reminders_due_time"), "reminders", ["due_time"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column(
            "week_boundary",
            sa.Enum(
                "MONDAY_FRIDAY",
                "SUNDAY_SATURDAY",
                "MONDAY_SUNDAY",
                name="weekboundary",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("working_hours_start", sa.Integer(), nullable=True),
        sa.Column("working_hours_end", sa.Integer(), nullable=True),
        sa.Column("communication_style", sa.String(length=1000), nullable=True),
        sa.Column("work_approach", sa.String(length=1000), nullable=True),
        sa.Column("profile_last_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "employment_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["person_id"], ["people.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("on_behalf_of_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "PAUSED", "COMPLETED", name="projectstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["on_behalf_of_id"], ["employers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=False)
    op.create_table(
        "meetings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("summary", sa.String(length=2000), nullable=True),
        sa.Column(
            "privacy_level",
            sa.Enum("PUBLIC", "INTERNAL", "PRIVATE", name="privacylevel", native_enum=False),
            nullable=False,
        ),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("meeting_type", sa.String(length=100), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_meetings_start_time"), "meetings", ["start_time"], unique=False)
    op.create_table(
        "work_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_hours", sa.Numeric(precision=4, scale=1), nullable=False),
        sa.Column("summary", sa.String(length=2000), nullable=True),
        sa.Column(
            "privacy_level",
            sa.Enum("PUBLIC", "INTERNAL", "PRIVATE", name="privacylevel", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_work_sessions_date"), "work_sessions", ["date"], unique=False)
    op.create_index(
        "ix_work_sessions_project_date", "work_sessions", ["project_id", "date"], unique=False
    )
    op.create_table(
        "meeting_attendees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["person_id"], ["people.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meeting_attendees")
    op.drop_index("ix_work_sessions_project_date", table_name="work_sessions")
    op.drop_index(op.f("ix_work_sessions_date"), table_name="work_sessions")
    op.drop_table("work_sessions")
    op.drop_index(op.f("ix_meetings_start_time"), table_name="meetings")
    op.drop_table("meetings")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_table("projects")
    op.drop_table("employment_history")
    op.drop_table("users")
    op.drop_index(op.f("ix_reminders_due_time"), table_name="reminders")
    op.drop_index("ix_reminders_active", table_name="reminders")
    op.drop_table("reminders")
    op.drop_index(op.f("ix_people_full_name"), table_name="people")
    op.drop_index(op.f("ix_people_email"), table_name="people")
    op.drop_table("people")
    op.drop_index("ix_notes_entity", table_name="notes")
    op.drop_table("notes")
    op.drop_index(op.f("ix_employers_name"), table_name="employers")
    op.drop_table("employers")
    op.drop_index(op.f("ix_clients_name"), table_name="clients")
    op.drop_table("clients")
    # ### end Alembic commands ###
